- name: installing httpd
  package:
          name: httpd
          state: present

- name: installing php
  package:
          name: php
          state: present

- name: copying webpage
  template:
          src: /root/task/index.php
          dest: /var/www/html

- name: starting httpd service
  service:
          name: httpd
          state: started
                
