- name: installing haproxy
  package:
          name: haproxy
          state: present

- name: copying config file
  template:
          src: haproxy.cfg
          dest: /etc/haproxy/haproxy.cfg
                    

- name: starting haproxy service
  service:
          name: haproxy
          state: started


